language: python
python: '2.7'
sudo: false
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl

install:
  - pip install --upgrade pip
  - pip install ansible
env:
  - PAPERTRAIL_TEST_HOSTNAME: localhost
    PAPERTRAIL_TEST_CONNECTION: local
    secure: PGVXCeE9z1rUXMnIh8td0dKNf0AgnzktiEsESrHEfWFWHNw08gym48roHual9+3QLx+T4dQ+ark0LQ2shTU/iYA8YG2JVK+Zo0tYUI3WhdiPWcFul4He2i+Jai+W6KNsmCivN2uVJVC+h43CCyNdKNtTgjmYs2CbbDaaQNIuDjKbvlGmlzuKEWi77LZa0O7ifVby6uAGboVYvvxHKs6cXfxexj66+frQ7aik+M4whpBbxf/OoB4he9Y7TqLj7dArN/esH0uk6VrGTEb5Yy4RkkVIjnXbF2YtYl31bZTPOKQh01tTLcXdMq4AEIY6P7pdgdF9wXOgOt3GzEogI/r0DvrUPk3ZZXEHW/9qr07Epcacprs4mp040EPVHc2CdZna1kB8RHbjOwSyVwmgang7k90vLxD7y9PmNax9J0oPF040OnqvMj++R2ZJHINPyquznhPYhr1wg/2R2TUBYop830FPzKrsaGTf6WRR5VqVKSkzrkytywg0l53HvhBITag1RQv5jDuf2Yzy8D2QctM7yC89MdB35cAsN/HScSSEYbOTowO7W8M+P3+T7SxZ7YfDobX0Cu2QVbxdQHWHNoksfu72OKWn5l5/jDFhHiVRbP/Ri+yO7LvT2av/ruiudNBovNzlHZBrrf+0ERc+NYi2T0TDQfHfDbbPSJIBvj2JgVY=
script:
- ansible-playbook --syntax-check -i test/inventory test/playbook.yml
- ansible-playbook -i test/inventory test/playbook.yml --connection=local --sudo -vvvv
