---
- name: Ensure rsyslog is installed on Debian flavours
  apt:
    name: rsyslog
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
    update_cache: "{{ papertrail_pkg_mgr_update_cache }}"
  when: ansible_pkg_mgr == 'apt' and papertrail_install_rsyslog

- name: Ensure rsyslog is installed on CentOS flavours
  yum:
    name: rsyslog
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
    update_cache: "{{ papertrail_pkg_mgr_update_cache }}"
  when: ansible_pkg_mgr == 'yum' and papertrail_install_rsyslog

- name: Ensure rsyslog-gnutls is installed on Debian flavours
  apt:
    name: rsyslog-gnutls
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
  when: ansible_pkg_mgr == 'apt' and papertrail_install_rsyslog_gnutls

- name: Ensure rsyslog-gnutls is installed on CentOS flavours
  yum:
    name: rsyslog-gnutls
    state: "{{ 'latest' if papertrail_pkg_mgr_install_latest else 'present' }}"
  when: ansible_pkg_mgr == 'yum' and papertrail_install_rsyslog_gnutls

...
