---
- name: Install rsyslog and gnutls if necessary
  include: install.yml

- name: Make the rsyslog.d directory
  file:
    path: "{{ papertrail_rsyslogd_conf_dir }}"
    state: directory
    mode: "{{ papertrail_rsyslogd_conf_dir_mode }}"
    owner: "{{ papertrail_rsyslogd_conf_dir_owner }}"
    group: "{{ papertrail_rsyslogd_conf_dir_group }}"
    recurse: "{{ papertrail_rsyslogd_conf_dir_recurse }}"

- name: Copy the template into place
  template:
    src: "{{ papertrail_rsyslog_conf_file_template }}"
    dest: "{{ papertrail_rsyslog_conf_file }}"
    mode: "{{ papertrail_rsyslogd_conf_file_mode }}"
    owner: "{{ papertrail_rsyslogd_conf_file_owner }}"
    group: "{{ papertrail_rsyslogd_conf_file_group }}"
  when: papertrail_rsyslog_conf_file_template is defined
  notify:
    - restart rsyslog


- name: Ensure the rsyslog.d directory is included
  lineinfile:
    state: present
    dest: "{{ papertrail_rsyslog_conf_file }}"
    line: "$IncludeConfig {{ papertrail_rsyslogd_conf_dir }}/*.conf"
  notify:
    - restart rsyslog

- name: Set up the certificate bundle and requirements if using secure mode
  include: certificate.yml
  when: papertrail_rsyslog_secure

- name: Put the papertrail config into the rsyslog.d directory
  template:
    src: "{{ papertrail_rsyslog_template }}"
    dest: "{{ papertrail_rsyslog_file }}"
    mode: "{{ papertrail_rsyslogd_file_mode }}"
    owner: "{{ papertrail_rsyslogd_file_owner }}"
    group: "{{ papertrail_rsyslogd_file_group  }}"
  notify:
    - restart rsyslog

...
